spring:
  application:
    name: TOYERP

  datasource:
    url: jdbc:postgresql://localhost:5432/TOYERP
    username: toyerp
    password: toyerp_pw
    driver-class-name: org.postgresql.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  config:
    import: optional:application-secret.yml

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 5000
    # password: your_redis_password  ← 필요시

server:
  port: 8080

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml
  type-aliases-package: com.example.toyerp.domain
